name: viralong-id
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.11
  - biopython
  - matplotlib
  - cartopy
  - ncbi-datasets-cli
  - blast
  - fastplong
  - flye
  - mafft
  - trimal
  - iqtree
  - openjdk=17
  - unzip
  - pip
