name: viralong-id
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - biopython
  - matplotlib
  - ncbi-datasets-cli
  - blast
  - fastplong
  - flye
  - mafft
  - trimal
  - iqtree
  - unzip
  - pip
